name = "teaven-email"
main = "src/index.ts"
compatibility_date = "2025-06-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "teaven-email-db"
database_id = "teaven-email-db-id"

[[kv_namespaces]]
binding = "KV"
id = "7f1ba6c1269d4f6ab0183443e6177555"

[[r2_buckets]]
binding = "R2"
bucket_name = "teaven-email-assets"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = ""

[observability]
enabled = true
